### ISSUE TITLE
能分享训练语料吗

### ISSUE THREAD

**Issue by SeekPoint** [valuesimplex/FinBERT#2]

**Comment by entropyreduce** [comment]
对于训练数据，脱敏之后可以点对点开放。

**Comment by liesun1994** [comment]
开放后可以顺便抄送一份给我吗，谢谢～   mail:   liesun1994@gmail.com

**Comment by SeekPoint** [comment]
yk_data@126.com

**Comment by MichaelCro** [comment]
> 对于训练数据，脱敏之后可以点对点开放。
开放后也可以顺便抄送一份给我吗，非常谢谢～ mail：chenguohao02@gmail.com

**Comment by MichaelCro** [comment]
> 对于训练数据，脱敏之后可以点对点开放。

1

**Comment by MichaelCro** [comment]
> 对于训练数据，脱敏之后可以点对点开放。

开放后也可以顺便抄送一份给我吗，非常谢谢～ mail：chenguohao02@gmail.com

**Comment by MichaelCro** [comment]
> 对于训练数据，脱敏之后可以点对点开放。

开放后也可以顺便抄送一份给我吗，非常感谢～ mail：chenguohao02@gmail.com

**Comment by wangy8989** [comment]
> 对于训练数据，脱敏之后可以点对点开放。

开放后也可以顺便抄送一份给我吗，非常感谢～ mail：wangyc6@mail.sustech.edu.cn

**Comment by eglantine719** [comment]
开放后可以发送一份我吗？非常感谢~727441749@qq.com

**Comment by ThetaRgo** [comment]
同求一份 492151773@qq.com

**Comment by Minqi824** [comment]
同求一份数据，万分感谢！jiangmq95@163.com

**Comment by SeekPoint** [comment]
别做梦了

**Comment by EvanHong99** [comment]
您好，我也非常需要这一份数据，非常感谢 939778128@qq.com

**Comment by kk19990709** [comment]
同求，kangkai1999@foxmail.com
